// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmKeHuCbzC3PptyxhJLE4ZDnYsSW8reNA',
    appId: '1:856877918512:web:bbbc2754dc6b3aae69c0f5',
    messagingSenderId: '856877918512',
    projectId: 'food-facts-e054d',
    authDomain: 'food-facts-e054d.firebaseapp.com',
    storageBucket: 'food-facts-e054d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkaXjIWxNvcR530FhvQcPLDdzjl2CojXk',
    appId: '1:856877918512:android:c45e62e74ec4e76b69c0f5',
    messagingSenderId: '856877918512',
    projectId: 'food-facts-e054d',
    storageBucket: 'food-facts-e054d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDV1q4KToB0NbbiyMoXFlXEFj_XRvifG7s',
    appId: '1:856877918512:ios:4eef12480618a77169c0f5',
    messagingSenderId: '856877918512',
    projectId: 'food-facts-e054d',
    storageBucket: 'food-facts-e054d.appspot.com',
    iosClientId: '856877918512-om72rkon7b4rkeiqcgrd9o0f9e92orce.apps.googleusercontent.com',
    iosBundleId: 'live.prashant.foodFacts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDV1q4KToB0NbbiyMoXFlXEFj_XRvifG7s',
    appId: '1:856877918512:ios:4eef12480618a77169c0f5',
    messagingSenderId: '856877918512',
    projectId: 'food-facts-e054d',
    storageBucket: 'food-facts-e054d.appspot.com',
    iosClientId: '856877918512-om72rkon7b4rkeiqcgrd9o0f9e92orce.apps.googleusercontent.com',
    iosBundleId: 'live.prashant.foodFacts',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmKeHuCbzC3PptyxhJLE4ZDnYsSW8reNA',
    appId: '1:856877918512:web:83c0e25fa7fb806c69c0f5',
    messagingSenderId: '856877918512',
    projectId: 'food-facts-e054d',
    authDomain: 'food-facts-e054d.firebaseapp.com',
    storageBucket: 'food-facts-e054d.appspot.com',
  );
}
